<a href="https://colab.research.google.com/github/abcdon21/dataCleaningPD/blob/main/Diabetes_SMOTE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# from google.colab import files
# uploaded= files.upload()

Saving diabetes.csv to diabetes.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('diabetes.csv')

In [5]:
X=df.drop('Outcome',axis=1)
y=df['Outcome']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
#counts no. of people have diabties and not
y_train.value_counts()

Outcome
0    401
1    213
Name: count, dtype: int64

In [8]:
#STANDANRD SCALER IS ALWAYS USED WITH SMOTE

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

SMOTE

In [10]:
from imblearn.over_sampling import SMOTE
oversampling= SMOTE(sampling_strategy='auto',k_neighbors=3)
X_train,y_train=oversampling.fit_resample(X_train,y_train)

In [11]:
y_train.value_counts()

Outcome
0    401
1    401
Name: count, dtype: int64