<a href="https://colab.research.google.com/github/abcdon21/dataCleaningPD/blob/main/SalaryData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
#from google.colab import files
#uploaded = files.upload()

Saving Salary_Data.csv to Salary_Data (1).csv

In [54]:
import numpy as np
import pandas as pd
df=pd.read_csv('Salary_Data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 314.3+ KB

In [55]:
df['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', "Bachelor's Degree",
       "Master's Degree", nan, 'High School', 'phD'], dtype=object)

In [56]:
df['Education Level']=df['Education Level'].replace("Bachelor's","Bachelor's Degree") #.unique() method in Pandas extracts all distinct values from a DataFrame column (Series).
df['Education Level'].unique()

array(["Bachelor's Degree", "Master's", 'PhD', "Master's Degree", nan,
       'High School', 'phD'], dtype=object)

In [57]:
df['Education Level']=df['Education Level'].replace("Master's","Master's Degree")
df['Education Level'].unique()

array(["Bachelor's Degree", "Master's Degree", 'PhD', nan, 'High School',
       'phD'], dtype=object)

In [58]:
df['Education Level']=df['Education Level'].replace("phD","PhD")
df['Education Level'].unique()

array(["Bachelor's Degree", "Master's Degree", 'PhD', nan, 'High School'],
      dtype=object)

In [59]:
df['Education Level']=df['Education Level'].fillna(df['Education Level'].mode()[0])

In [60]:
df['Years of Experience'].skew()

np.float64(0.981187602540142)

In [61]:
df['Years of Experience']=df['Years of Experience'].fillna(df['Years of Experience'].mean())

In [62]:
df['Salary'].skew()

np.float64(0.05734392354615517)

In [63]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Gender               6702 non-null   object
 2   Education Level      6702 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6702 non-null   float64
 5   Salary               6702 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 314.3+ KB

In [65]:
df= pd.get_dummies(df,columns=['Gender'],drop_first= True)#forms dummy column of one orignal column
print(df)

      Age    Education Level  ... Gender_Male  Gender_Other
0      32  Bachelor's Degree  ...        True         False
1      28    Master's Degree  ...       False         False
2      45                PhD  ...        True         False
3      36  Bachelor's Degree  ...       False         False
4      52    Master's Degree  ...        True         False
...   ...                ...  ...         ...           ...
6697   49                PhD  ...       False         False
6698   32        High School  ...        True         False
6699   30  Bachelor's Degree  ...       False         False
6700   46    Master's Degree  ...        True         False
6701   26        High School  ...       False         False

[6702 rows x 7 columns]

ORDINAL ENCODING - a data preprocessing technique that converts categorical text data into numerical values by assigning a unique, ordered integer to each category.

In [66]:
from sklearn.preprocessing import OrdinalEncoder

oe= OrdinalEncoder(categories=[["High School","Bachelor's Degree","Master's Degree","PhD"]])#object creation

df['Education Level']=oe.fit_transform(df[['Education Level']]) #find and transform

df.head()

   Age  Education Level          Job Title  ...    Salary  Gender_Male  Gender_Other
0   32              1.0  Software Engineer  ...   90000.0         True         False
1   28              2.0       Data Analyst  ...   65000.0        False         False
2   45              3.0     Senior Manager  ...  150000.0         True         False
3   36              1.0    Sales Associate  ...   60000.0        False         False
4   52              2.0           Director  ...  200000.0         True         False

[5 rows x 7 columns]

In [67]:
df['Job Title'].unique()

array(['Software Engineer', 'Data Analyst', 'Senior Manager',
       'Sales Associate', 'Director', 'Marketing Analyst',
       'Product Manager', 'Sales Manager', 'Marketing Coordinator',
       'Senior Scientist', 'Software Developer', 'HR Manager',
       'Financial Analyst', 'Project Manager', 'Customer Service Rep',
       'Operations Manager', 'Marketing Manager', 'Senior Engineer',
       'Data Entry Clerk', 'Sales Director', 'Business Analyst',
       'VP of Operations', 'IT Support', 'Recruiter', 'Financial Manager',
       'Social Media Specialist', 'Software Manager', 'Junior Developer',
       'Senior Consultant', 'Product Designer', 'CEO', 'Accountant',
       'Data Scientist', 'Marketing Specialist', 'Technical Writer',
       'HR Generalist', 'Project Engineer', 'Customer Success Rep',
       'Sales Executive', 'UX Designer', 'Operations Director',
       'Network Engineer', 'Administrative Assistant',
       'Strategy Consultant', 'Copywriter', 'Account Manager',
       'Director of Marketing', 'Help Desk Analyst',
       'Customer Service Manager', 'Business Intelligence Analyst',
       'Event Coordinator', 'VP of Finance', 'Graphic Designer',
       'UX Researcher', 'Social Media Manager', 'Director of Operations',
       'Senior Data Scientist', 'Junior Accountant',
       'Digital Marketing Manager', 'IT Manager',
       'Customer Service Representative', 'Business Development Manager',
       'Senior Financial Analyst', 'Web Developer', 'Research Director',
       'Technical Support Specialist', 'Creative Director',
       'Senior Software Engineer', 'Human Resources Director',
       'Content Marketing Manager', 'Technical Recruiter',
       'Sales Representative', 'Chief Technology Officer',
       'Junior Designer', 'Financial Advisor', 'Junior Account Manager',
       'Senior Project Manager', 'Principal Scientist',
       'Supply Chain Manager', 'Senior Marketing Manager',
       'Training Specialist', 'Research Scientist',
       'Junior Software Developer', 'Public Relations Manager',
       'Operations Analyst', 'Product Marketing Manager',
       'Senior HR Manager', 'Junior Web Developer',
       'Senior Project Coordinator', 'Chief Data Officer',
       'Digital Content Producer', 'IT Support Specialist',
       'Senior Marketing Analyst', 'Customer Success Manager',
       'Senior Graphic Designer', 'Software Project Manager',
       'Supply Chain Analyst', 'Senior Business Analyst',
       'Junior Marketing Analyst', 'Office Manager', 'Principal Engineer',
       'Junior HR Generalist', 'Senior Product Manager',
       'Junior Operations Analyst', 'Senior HR Generalist',
       'Sales Operations Manager', 'Senior Software Developer',
       'Junior Web Designer', 'Senior Training Specialist',
       'Senior Research Scientist', 'Junior Sales Representative',
       'Junior Marketing Manager', 'Junior Data Analyst',
       'Senior Product Marketing Manager', 'Junior Business Analyst',
       'Senior Sales Manager', 'Junior Marketing Specialist',
       'Junior Project Manager', 'Senior Accountant', 'Director of Sales',
       'Junior Recruiter', 'Senior Business Development Manager',
       'Senior Product Designer', 'Junior Customer Support Specialist',
       'Senior IT Support Specialist', 'Junior Financial Analyst',
       'Senior Operations Manager', 'Director of Human Resources',
       'Junior Software Engineer', 'Senior Sales Representative',
       'Director of Product Management', 'Junior Copywriter',
       'Senior Marketing Coordinator', 'Senior Human Resources Manager',
       'Junior Business Development Associate', 'Senior Account Manager',
       'Senior Researcher', 'Junior HR Coordinator',
       'Director of Finance', 'Junior Marketing Coordinator',
       'Junior Data Scientist', 'Senior Operations Analyst',
       'Senior Human Resources Coordinator', 'Senior UX Designer',
       'Junior Product Manager', 'Senior Marketing Specialist',
       'Senior IT Project Manager', 'Senior Quality Assurance Analyst',
       'Director of Sales and Marketing', 'Senior Account Executive',
       'Director of Business Development', 'Junior Social Media Manager',
       'Senior Human Resources Specialist', 'Senior Data Analyst',
       'Director of Human Capital', 'Junior Advertising Coordinator',
       'Junior UX Designer', 'Senior Marketing Director',
       'Senior IT Consultant', 'Senior Financial Advisor',
       'Junior Business Operations Analyst',
       'Junior Social Media Specialist',
       'Senior Product Development Manager', 'Junior Operations Manager',
       'Senior Software Architect', 'Junior Research Scientist',
       'Senior Financial Manager', 'Senior HR Specialist',
       'Senior Data Engineer', 'Junior Operations Coordinator',
       'Director of HR', 'Senior Operations Coordinator',
       'Junior Financial Advisor', 'Director of Engineering',
       'Software Engineer Manager', 'Back end Developer',
       'Senior Project Engineer', 'Full Stack Engineer',
       'Front end Developer', 'Developer', 'Front End Developer',
       'Director of Data Science', 'Human Resources Coordinator',
       'Junior Sales Associate', 'Human Resources Manager',
       'Juniour HR Generalist', 'Juniour HR Coordinator',
       'Digital Marketing Specialist', 'Receptionist',
       'Marketing Director', 'Social M', 'Social Media Man',
       'Delivery Driver'], dtype=object)

In [68]:
df['Salary'].max()

250000.0

In [69]:
#feature
X=df[['Age','Education Level','Years of Experience']]
#target
y=df['Salary']

In [70]:
y.head()

0     90000.0
1     65000.0
2    150000.0
3     60000.0
4    200000.0
Name: Salary, dtype: float64

In [71]:
from sklearn.model_selection import train_test_split #TTS machine learning technique that divides your dataset into two distinct subsets: a training set used to teach your model patterns, and a testing set

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

feature scaling are of two types
1. NORMALIZATION
2. STANDARDLIZATION


(except decision tree and random forest no feature scaling is applied)
jis column mei khud sei encoding ki hai manually yaa true yaa false wala section ho waha feature scaling nahi lagti hi

In [72]:
from sklearn.preprocessing import MinMaxScaler

scaler= MinMaxScaler()

X_train[["Age",'Years of Experience']]= scaler.fit_transform(X_train[["Age",'Years of Experience']])

X_test[["Age",'Years of Experience']]= scaler.transform(X_test[["Age",'Years of Experience']])

X_train.head()

           Age  Education Level  Years of Experience
4939  0.121951              1.0             0.147059
135   0.439024              1.0             0.294118
2251  0.024390              1.0             0.029412
3428  0.268293              1.0             0.058824
5356  0.146341              1.0             0.058824

MODEL TRAINING

In [73]:
from sklearn.linear_model import LinearRegression

model= LinearRegression()

model.fit(X_train, y_train)

y_pred= model.predict(X_test)

In [74]:
print(y_pred)
print(y_test)

[119603.14070126 177613.8023635   77922.28858654 ... 161277.34171754
 167408.77991271  67715.04910294]
5071    120000.0
4462    157000.0
5557     80000.0
6540     40000.0
263      40000.0
          ...
2155    185000.0
2298    180000.0
3505    140000.0
5632    170000.0
2984     55935.0
Name: Salary, Length: 1341, dtype: float64

SALARY=b0 + b1.age + b2.years of experience + b3.education encoded

EVALUATION METRICES

1.mean absolute error- avg of errors at each point

2.mean squared error- square of error at each point calculating their avg

3.R2 score-

In [75]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [76]:
mae = mean_absolute_error(y_pred, y_test)
print(mae)

22145.305585243244

In [77]:
mse= mean_squared_error(y_pred, y_test)
print(mse)

810907388.476432

In [78]:
r2= r2_score(y_pred, y_test)
print(r2)

0.5908484284253008

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Education Level      6702 non-null   float64
 2   Job Title            6702 non-null   object
 3   Years of Experience  6702 non-null   float64
 4   Salary               6702 non-null   float64
 5   Gender_Male          6702 non-null   bool
 6   Gender_Other         6702 non-null   bool
dtypes: bool(2), float64(3), int64(1), object(1)
memory usage: 275.0+ KB

In [80]:
def user_input():
  age=int(input("Enter Age: "))
  edu= float(input("Enter Education Level: "))
  exp= float(input("Enter Years of Experience: "))

  #create a dataframe
  user =pd.DataFrame([[age,edu,exp]],columns=['Age','Education Level','Years of Experience'])
  user_prediction= model.predict(user)
  print("predicted salary",user_prediction[0])

In [81]:
user_input()

Enter Age: 50
Enter Education Level: 1
Enter Years of Experience: 1
predicted salary -3843429.082334893